# Generated by Django 5.0.4 on 2024-07-05 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_item_phone_item_agency_em_item_blood_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='address',
        ),
        migrations.RemoveField(
            model_name='item',
            name='employment_status',
        ),
    ]
