# Generated by Django 5.0.4 on 2024-07-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_item_civil_status_alter_item_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A_POSITIVE', 'A+'), ('A_NEGATIVE', 'A-'), ('B_POSITIVE', 'B+'), ('B_NEGATIVE', 'B-'), ('O_POSITIVE', 'O+'), ('O_NEGATIVE', 'O-'), ('AB_POSITIVE', 'AB+'), ('AB_NEGATIVE', 'AB-'), ('UNKNOWN', 'Unknown')], max_length=11, null=True),
        ),
    ]
